### ISSUE TITLE
Arrange all images in similarity-order but in same folder - for example rename them in accordance to similarity

### ISSUE THREAD

**Issue by aggoaggo** [victorqribeiro/groupImg#4]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by victorqribeiro** [comment]
If you pass the flag -m (move) all the images will be moved to a folder with all the other similar images. On top of that would you like to rename them? I don't think the script should do that, as it can be easily done with the batch rename (all linux distros comes with a default one installed)

**Comment by aggoaggo** [comment]
Well, I would like to sort ALL images in "similarity" order if you understand what I mean. Saying I have 100 images, I would like to sort them from 1 to 100 in similarity order, for example by renaming them 1-100, where image 1 being most similar to image 2, and then image 3 being second most similar to 1.

**Comment by victorqribeiro** [comment]
Well, that's another "beast". You can use part of my code to do that. But instead of grouping images by similarity, you would choose ONE image to be your reference and ORDER all the other ones by similarity to the ONE image. 

an algorithm would look like this:

```
reference_image := "Image you want as reference"

for image in list_of_images:

    measure the distance between image and reference_image

return the list of images ordered small to big
```

The first ones will be more similar to reference, the last ones the most different

**Comment by aggoaggo** [comment]
Great, thanks! Will try to implement that!

**Comment by plagasul** [comment]
@aggoaggo did you ever implemented that? Sounds interesting, would like to test :))
